"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-19 17:46:50.038737
"""

from __future__ import annotations

from collections.abc import Sequence

import app.models.base
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "companies",
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column("user_id", app.models.base.GUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_companies_industry"), ["industry"], unique=False)
        batch_op.create_index(batch_op.f("ix_companies_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_companies_user_id_name", ["user_id", "name"], unique=False)

    op.create_table(
        "applications",
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column("user_id", app.models.base.GUID(), nullable=False),
        sa.Column("company_id", app.models.base.GUID(), nullable=True),
        sa.Column("role_title", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "wishlist",
                "applied",
                "assessment",
                "interview",
                "final_interview",
                "offer",
                "rejected",
                "accepted",
                name="application_status",
            ),
            nullable=False,
        ),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column("salary_currency", sa.String(length=3), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("is_remote", sa.Boolean(), nullable=False),
        sa.Column("application_url", sa.String(length=1000), nullable=True),
        sa.Column("source", sa.String(length=120), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "salary_min IS NULL OR salary_max IS NULL OR salary_max >= salary_min",
            name="ck_applications_salary_range",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_applications_company_id"), ["company_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_applications_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_applications_user_id_status", ["user_id", "status"], unique=False)

    op.create_table(
        "attachments",
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column("user_id", app.models.base.GUID(), nullable=False),
        sa.Column("application_id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("resume", "cover_letter", "other", name="attachment_kind"),
            nullable=False,
        ),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("attachments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attachments_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_attachments_user_id"), ["user_id"], unique=False)

    op.create_table(
        "interviews",
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column("user_id", app.models.base.GUID(), nullable=False),
        sa.Column("application_id", app.models.base.GUID(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("round_type", sa.String(length=80), nullable=True),
        sa.Column("interviewer", sa.String(length=200), nullable=True),
        sa.Column(
            "mode", sa.Enum("phone", "video", "onsite", name="interview_mode"), nullable=False
        ),
        sa.Column(
            "result",
            sa.Enum("pending", "passed", "failed", "cancelled", name="interview_result"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("interviews", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_interviews_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_interviews_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_interviews_user_id_scheduled_at", ["user_id", "scheduled_at"], unique=False
        )

    op.create_table(
        "notes",
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column("user_id", app.models.base.GUID(), nullable=False),
        sa.Column("application_id", app.models.base.GUID(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notes_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notes_user_id"), ["user_id"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column("user_id", app.models.base.GUID(), nullable=False),
        sa.Column("application_id", app.models.base.GUID(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "priority", sa.Enum("low", "medium", "high", name="task_priority"), nullable=False
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tasks_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tasks_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_tasks_user_id_due_at", ["user_id", "due_at"], unique=False)
        batch_op.create_index(
            "ix_tasks_user_id_is_completed", ["user_id", "is_completed"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_tasks_user_id_is_completed")
        batch_op.drop_index("ix_tasks_user_id_due_at")
        batch_op.drop_index(batch_op.f("ix_tasks_user_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_application_id"))

    op.drop_table("tasks")
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notes_user_id"))
        batch_op.drop_index(batch_op.f("ix_notes_application_id"))

    op.drop_table("notes")
    with op.batch_alter_table("interviews", schema=None) as batch_op:
        batch_op.drop_index("ix_interviews_user_id_scheduled_at")
        batch_op.drop_index(batch_op.f("ix_interviews_user_id"))
        batch_op.drop_index(batch_op.f("ix_interviews_application_id"))

    op.drop_table("interviews")
    with op.batch_alter_table("attachments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attachments_user_id"))
        batch_op.drop_index(batch_op.f("ix_attachments_application_id"))

    op.drop_table("attachments")
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_index("ix_applications_user_id_status")
        batch_op.drop_index(batch_op.f("ix_applications_user_id"))
        batch_op.drop_index(batch_op.f("ix_applications_company_id"))

    op.drop_table("applications")
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.drop_index("ix_companies_user_id_name")
        batch_op.drop_index(batch_op.f("ix_companies_user_id"))
        batch_op.drop_index(batch_op.f("ix_companies_industry"))

    op.drop_table("companies")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
