"""add offers table

Revision ID: 0002_offers
Revises: 0001_initial
Create Date: 2026-06-23 21:23:13.720523
"""

from __future__ import annotations

from collections.abc import Sequence

import app.models.base
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002_offers"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offers",
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column("user_id", app.models.base.GUID(), nullable=False),
        sa.Column("application_id", app.models.base.GUID(), nullable=False),
        sa.Column("base_salary", sa.Integer(), nullable=True),
        sa.Column("bonus", sa.Integer(), nullable=True),
        sa.Column("equity", sa.String(length=200), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("benefits", sa.Text(), nullable=True),
        sa.Column(
            "decision",
            sa.Enum("pending", "negotiating", "accepted", "declined", name="offer_decision"),
            nullable=False,
        ),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("offers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_offers_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_offers_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("offers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_offers_user_id"))
        batch_op.drop_index(batch_op.f("ix_offers_application_id"))

    op.drop_table("offers")
    # ### end Alembic commands ###
