"""smart job search: cvs, certificates, skills, jobs, filters, sourced applications, automation

Revision ID: ff0908657d2c
Revises: 0002_offers
Create Date: 2026-06-25 02:00:00.122893
"""

from __future__ import annotations

from collections.abc import Sequence

import app.models.base
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003_smart_job_search"
down_revision: str | None = "0002_offers"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certificates",
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column("user_id", app.models.base.GUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("issuer", sa.String(length=200), nullable=True),
        sa.Column("issued_on", sa.Date(), nullable=True),
        sa.Column("credential_url", sa.String(length=500), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("stored_filename", sa.String(length=255), nullable=True),
        sa.Column("content_type", sa.String(length=120), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("certificates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_certificates_user_id"), ["user_id"], unique=False)

    op.create_table(
        "job_search_filters",
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column("user_id", app.models.base.GUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("title_keywords", sa.String(length=500), nullable=True),
        sa.Column("locations", sa.String(length=500), nullable=True),
        sa.Column("keywords", sa.String(length=500), nullable=True),
        sa.Column("remote", sa.Boolean(), nullable=False),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_search_filters", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_job_search_filters_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "jobs",
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column("user_id", app.models.base.GUID(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("company", sa.String(length=200), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column("remote", sa.Boolean(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "source", "external_id", name="uq_job_user_source_external"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "skills",
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column("user_id", app.models.base.GUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column(
            "proficiency",
            sa.Enum("beginner", "intermediate", "advanced", "expert", name="skill_proficiency"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_skill_user_name"),
    )
    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_skills_user_id"), ["user_id"], unique=False)

    op.create_table(
        "automation_rules",
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column("user_id", app.models.base.GUID(), nullable=False),
        sa.Column("filter_id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "run_frequency",
            sa.Enum("manual", "daily", "weekly", name="run_frequency"),
            nullable=False,
        ),
        sa.Column("max_applications_per_run", sa.Integer(), nullable=False),
        sa.Column("auto_tailor_cv", sa.Boolean(), nullable=False),
        sa.Column("auto_create_application", sa.Boolean(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["filter_id"], ["job_search_filters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("automation_rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_automation_rules_filter_id"), ["filter_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_automation_rules_user_id"), ["user_id"], unique=False)

    op.create_table(
        "cvs",
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column("user_id", app.models.base.GUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("source", sa.Enum("uploaded", "ai_tailored", name="cv_source"), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("stored_filename", sa.String(length=255), nullable=True),
        sa.Column("content_type", sa.String(length=120), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("content_text", sa.Text(), nullable=True),
        sa.Column("parent_cv_id", app.models.base.GUID(), nullable=True),
        sa.Column("job_id", app.models.base.GUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_cv_id"], ["cvs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cvs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cvs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "sourced_applications",
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column("user_id", app.models.base.GUID(), nullable=False),
        sa.Column("job_id", app.models.base.GUID(), nullable=False),
        sa.Column("cv_id", app.models.base.GUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "saved",
                "applied",
                "interviewing",
                "rejected",
                "offer",
                "accepted",
                "withdrawn",
                name="sourced_application_status",
            ),
            nullable=False,
        ),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("cover_letter_text", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["cv_id"], ["cvs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sourced_applications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sourced_applications_job_id"), ["job_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sourced_applications_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sourced_applications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sourced_applications_user_id"))
        batch_op.drop_index(batch_op.f("ix_sourced_applications_job_id"))

    op.drop_table("sourced_applications")
    with op.batch_alter_table("cvs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cvs_user_id"))

    op.drop_table("cvs")
    with op.batch_alter_table("automation_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_automation_rules_user_id"))
        batch_op.drop_index(batch_op.f("ix_automation_rules_filter_id"))

    op.drop_table("automation_rules")
    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skills_user_id"))

    op.drop_table("skills")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_user_id"))

    op.drop_table("jobs")
    with op.batch_alter_table("job_search_filters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_search_filters_user_id"))

    op.drop_table("job_search_filters")
    with op.batch_alter_table("certificates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_certificates_user_id"))

    op.drop_table("certificates")
    # ### end Alembic commands ###
